/**
 * Transport Schemas - Zod validation for all Socket.IO payloads.
 *
 * Architecture:
 * - Zod schemas provide runtime validation for transport messages
 * - Types are inferred from schemas (single source of truth)
 * - All schemas are self-contained (no external dependencies)
 *
 * Usage:
 * ```typescript
 * import { TaskCreateRequestSchema } from '@campfirein/brv-transport-client'
 *
 * // Validate incoming data
 * const result = TaskCreateRequestSchema.safeParse(data)
 * if (!result.success) {
 *   console.error('Invalid payload:', result.error)
 * }
 * ```
 */
import {z} from 'zod'

import {CLIENT_TYPES} from '../../core/domain/types.js'

// ============================================================================
// Common Enums and Base Types
// ============================================================================

/**
 * Token usage statistics from LLM.
 */
export const TokenUsageSchema = z.object({
  inputTokens: z.number().int().nonnegative(),
  outputTokens: z.number().int().nonnegative(),
  totalTokens: z.number().int().nonnegative(),
})

/**
 * Log levels for agent logging.
 */
export const LogLevelSchema = z.enum(['debug', 'info', 'warn', 'error'])

/**
 * UI event types for terminal output.
 */
export const UIEventTypeSchema = z.enum(['banner', 'help', 'prompt', 'response', 'separator', 'shutdown'])

/**
 * Chunk content types for streaming.
 */
export const ChunkTypeSchema = z.enum(['text', 'reasoning'])

/**
 * Task types supported by the system.
 */
export const TaskTypeSchema = z.enum(['curate', 'query'])

/**
 * Todo item status.
 */
export const TodoStatusSchema = z.enum(['pending', 'in_progress', 'completed', 'cancelled'])

/**
 * Tool execution error types.
 */
export const ToolErrorTypeSchema = z.enum([
  'TOOL_NOT_FOUND',
  'TOOL_DISABLED',
  'INVALID_PARAMS',
  'INVALID_PARAM_TYPE',
  'MISSING_REQUIRED_PARAM',
  'PARAM_VALIDATION_FAILED',
  'EXECUTION_FAILED',
  'TIMEOUT',
  'PERMISSION_DENIED',
  'CONFIRMATION_REJECTED',
  'CANCELLED',
  'INTERNAL_ERROR',
  'PROVIDER_ERROR',
])

/**
 * Reasons for agent execution termination.
 */
export const AgentTerminationReasonSchema = z.enum([
  'GOAL',
  'MAX_TURNS',
  'TIMEOUT',
  'ABORTED',
  'ERROR',
  'PROTOCOL_VIOLATION',
])

// ============================================================================
// Shared Structures
// ============================================================================

/**
 * Todo item structure.
 */
export const TodoItemSchema = z.object({
  content: z.string().min(1),
  status: TodoStatusSchema,
  activeForm: z.string().min(1),
})

/**
 * Structured error data.
 */
export const TaskErrorDataSchema = z.object({
  name: z.string(),
  message: z.string(),
  code: z.string().optional(),
  details: z.record(z.unknown()).optional(),
})

/**
 * Daemon instance info schema for global daemon discovery.
 * Validates daemon.json structure for DaemonInstanceDiscovery.
 *
 * Required fields:
 * - pid: Process ID of daemon (positive integer)
 * - port: Transport server port (1024-65535)
 * - startedAt: Unix timestamp in milliseconds (positive integer)
 *
 * Note: Uses .strict() to reject unknown fields (defense in depth).
 */
export const DaemonInstanceSchema = z
  .object({
    pid: z.number().int().positive(),
    port: z.number().int().min(1024).max(65535),
    startedAt: z.number().int().positive(),
    version: z.string().optional(),
  })
  .strict()

// ============================================================================
// Task Event Payloads (task:*)
// ============================================================================

/**
 * task:create - Request to create a new task
 */
export const TaskCreateRequestSchema = z.object({
  /** Unique task ID (UUID v4, generated by client) */
  taskId: z.string().uuid('Invalid taskId format - must be UUID'),
  /** Task type (curate or query) */
  type: TaskTypeSchema,
  /** Task content/prompt */
  content: z.string().min(1, 'Content cannot be empty'),
  /** Optional file paths for curate --files (max 5) */
  files: z.array(z.string()).max(5).optional(),
  /** Client's working directory for file validation */
  clientCwd: z.string().optional(),
})

/**
 * task:ack - Server acknowledges task creation
 */
export const TaskAckSchema = z.object({
  taskId: z.string(),
})

/**
 * task:created - Broadcast when new task is created
 */
export const TaskCreatedSchema = z.object({
  taskId: z.string(),
  type: TaskTypeSchema,
  content: z.string(),
  files: z.array(z.string()).optional(),
  clientCwd: z.string().optional(),
})

/**
 * task:execute - Internal: Transport → Agent
 */
export const TaskExecuteSchema = z.object({
  taskId: z.string(),
  type: TaskTypeSchema,
  content: z.string(),
  clientId: z.string(),
  files: z.array(z.string()).optional(),
  clientCwd: z.string().optional(),
})

/**
 * task:started - Agent began processing
 */
export const TaskStartedSchema = z.object({
  taskId: z.string(),
  type: z.string().optional(),
  content: z.string().optional(),
  files: z.array(z.string()).optional(),
  clientCwd: z.string().optional(),
})

/**
 * task:completed - Task finished successfully
 */
export const TaskCompletedSchema = z.object({
  taskId: z.string(),
  result: z.string(),
})

/**
 * task:error - Task failed with error
 */
export const TaskErrorSchema = z.object({
  taskId: z.string(),
  error: TaskErrorDataSchema,
})

/**
 * task:cancel - Request to cancel a task
 */
export const TaskCancelRequestSchema = z.object({
  taskId: z.string(),
})

/**
 * task:cancel response
 */
export const TaskCancelResponseSchema = z.object({
  success: z.boolean(),
  error: z.string().optional(),
})

/**
 * task:cancelled - Task was cancelled
 */
export const TaskCancelledSchema = z.object({
  taskId: z.string(),
})

// ============================================================================
// LLM Event Payloads (llmservice:*)
// ============================================================================

/**
 * llmservice:thinking - Agent started thinking
 */
export const LlmThinkingSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
})

/**
 * llmservice:chunk - Streaming content chunk
 */
export const LlmChunkSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  type: ChunkTypeSchema,
  content: z.string(),
  isComplete: z.boolean().optional(),
})

/**
 * llmservice:response - Complete LLM response
 */
export const LlmResponseSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  content: z.string(),
  reasoning: z.string().optional(),
  model: z.string().optional(),
  provider: z.string().optional(),
  partial: z.boolean().optional(),
  tokenUsage: TokenUsageSchema.optional(),
})

/**
 * llmservice:toolCall - Agent invokes a tool
 */
export const LlmToolCallSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  toolName: z.string(),
  args: z.record(z.unknown()),
  callId: z.string().optional(),
})

/**
 * llmservice:toolResult - Tool execution result
 */
export const LlmToolResultSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  toolName: z.string(),
  success: z.boolean(),
  result: z.unknown().optional(),
  error: z.string().optional(),
  errorType: ToolErrorTypeSchema.optional(),
  metadata: z.record(z.unknown()).optional(),
  callId: z.string().optional(),
})

/**
 * llmservice:error - LLM service error
 */
export const LlmErrorSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  error: z.string(),
  code: z.string().optional(),
})

/**
 * llmservice:unsupportedInput - Input not supported
 */
export const LlmUnsupportedInputSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  reason: z.string(),
})

/**
 * llmservice:warning - Non-fatal warning
 */
export const LlmWarningSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  message: z.string(),
  model: z.string().optional(),
  provider: z.string().optional(),
})

/**
 * llmservice:outputTruncated - Output was truncated
 */
export const LlmOutputTruncatedSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  toolName: z.string(),
  originalLength: z.number().int().positive(),
  savedToFile: z.string(),
})

/**
 * llmservice:thought - Agent reasoning thought
 */
export const LlmThoughtSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  subject: z.string(),
  description: z.string(),
})

/**
 * llmservice:todoUpdated - Todo list was updated
 */
export const LlmTodoUpdatedSchema = z.object({
  sessionId: z.string(),
  taskId: z.string().optional(),
  todos: z.array(TodoItemSchema),
})

// ============================================================================
// Cipher Agent Event Payloads (cipher:*)
// ============================================================================

/**
 * cipher:executionStarted - Agent execution started
 */
export const CipherExecutionStartedSchema = z.object({
  sessionId: z.string(),
  startTime: z.coerce.date(),
  maxIterations: z.number().int().positive(),
  maxTimeMs: z.number().int().positive().optional(),
})

/**
 * cipher:executionTerminated - Agent execution ended
 */
export const CipherExecutionTerminatedSchema = z.object({
  sessionId: z.string(),
  endTime: z.coerce.date(),
  reason: AgentTerminationReasonSchema,
  turnCount: z.number().int().nonnegative(),
  toolCallsExecuted: z.number().int().nonnegative(),
  durationMs: z.number().int().nonnegative().optional(),
  error: z.any().optional(),
})

/**
 * cipher:conversationReset - Conversation was reset
 */
export const CipherConversationResetSchema = z.object({
  sessionId: z.string(),
})

/**
 * cipher:stateChanged - Agent state changed
 */
export const CipherStateChangedSchema = z.object({
  sessionId: z.string().optional(),
  field: z.string(),
  oldValue: z.unknown().optional(),
  newValue: z.unknown(),
})

/**
 * cipher:stateReset - Agent state was reset
 */
export const CipherStateResetSchema = z.object({
  sessionId: z.string().optional(),
})

/**
 * cipher:log - Agent log message
 */
export const CipherLogSchema = z.object({
  sessionId: z.string().optional(),
  level: LogLevelSchema,
  message: z.string(),
  source: z.string().optional(),
  context: z.record(z.unknown()).optional(),
})

/**
 * cipher:ui - UI event
 */
export const CipherUISchema = z.object({
  sessionId: z.string().optional(),
  type: UIEventTypeSchema,
  message: z.string().optional(),
  context: z.record(z.unknown()).optional(),
})

// ============================================================================
// Session Event Payloads (session:*)
// ============================================================================

/**
 * Session information structure.
 */
export const SessionInfoSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  createdAt: z.number().int().positive(),
  lastActiveAt: z.number().int().positive(),
})

/**
 * Session statistics.
 */
export const SessionStatsSchema = z.object({
  totalTasks: z.number().int().nonnegative(),
  completedTasks: z.number().int().nonnegative(),
  failedTasks: z.number().int().nonnegative(),
})

/**
 * session:info request (empty)
 */
export const SessionInfoRequestSchema = z.object({})

/**
 * session:info response
 */
export const SessionInfoResponseSchema = z.object({
  session: SessionInfoSchema,
  stats: SessionStatsSchema,
})

/**
 * session:list request (empty)
 */
export const SessionListRequestSchema = z.object({})

/**
 * session:list response
 */
export const SessionListResponseSchema = z.object({
  sessions: z.array(SessionInfoSchema),
})

/**
 * session:create request
 */
export const SessionCreateRequestSchema = z.object({
  name: z.string().optional(),
})

/**
 * session:create response
 */
export const SessionCreateResponseSchema = z.object({
  sessionId: z.string(),
})

/**
 * session:switch request
 */
export const SessionSwitchRequestSchema = z.object({
  sessionId: z.string(),
})

/**
 * session:switch response
 */
export const SessionSwitchResponseSchema = z.object({
  success: z.boolean(),
})

/**
 * session:switched broadcast
 */
export const SessionSwitchedBroadcastSchema = z.object({
  sessionId: z.string(),
})

// ============================================================================
// Agent Control Payloads (agent:*)
// ============================================================================

/**
 * agent:restart request
 */
export const AgentRestartRequestSchema = z.object({
  reason: z.string().optional(),
})

/**
 * agent:restart response
 */
export const AgentRestartResponseSchema = z.object({
  success: z.boolean(),
  error: z.string().optional(),
})

/**
 * agent:newSession request
 */
export const AgentNewSessionRequestSchema = z.object({
  reason: z.string().optional(),
})

/**
 * agent:newSession response
 */
export const AgentNewSessionResponseSchema = z.object({
  success: z.boolean(),
  sessionId: z.string().optional(),
  error: z.string().optional(),
})

/**
 * agent:status payload (health check)
 */
export const AgentStatusSchema = z.object({
  isInitialized: z.boolean(),
  hasAuth: z.boolean(),
  hasConfig: z.boolean(),
  activeTasks: z.number().int().nonnegative(),
  queuedTasks: z.number().int().nonnegative(),
  lastError: z.string().optional(),
})

// ============================================================================
// Client Registration Payloads (client:*)
// ============================================================================

/**
 * Client type for registration.
 * Derives from CLIENT_TYPES in domain layer (single source of truth).
 */
export const ClientTypeSchema = z.enum(CLIENT_TYPES)

/**
 * client:register request
 */
export const ClientRegisterRequestSchema = z.object({
  clientType: ClientTypeSchema,
  projectPath: z.string().optional(),
})

/**
 * client:register response
 */
export const ClientRegisterResponseSchema = z.object({
  success: z.boolean(),
  error: z.string().optional(),
})
